package torretromp_p1;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana_Materiales = new javax.swing.JDialog();
        PaneldePaneles = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablamaterialver = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labelerroragregarmaterial = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Tf_Numseriematerial = new javax.swing.JTextField();
        Tf_marcamaterial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ta_descripcionmaterial = new javax.swing.JTextArea();
        Tf_nombrematerial = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_eliminarmateriales = new javax.swing.JTable();
        btn_eliminarmaterial = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Cb_materialamodificar = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        Tf_nombrematerialmodif = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ta_descripcionmaterialmodif = new javax.swing.JTextArea();
        Tf_marcamaterialmodif = new javax.swing.JTextField();
        Tf_Numseriematerialmodif = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        Vnetana_Empleados = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabla_empleadosver = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tf_nombreempleados = new javax.swing.JTextField();
        tf_identidadempleados = new javax.swing.JTextField();
        tf_direccionempleados = new javax.swing.JTextField();
        tf_salarioempleado = new javax.swing.JTextField();
        tf_edadempleados = new javax.swing.JTextField();
        bt_agregarempleado = new javax.swing.JToggleButton();
        jLabel40 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        tf_salarioempleadomodif = new javax.swing.JTextField();
        tf_edadempleadomodif = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tf_identidadempleadomodif = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tf_direccionempleadomodif = new javax.swing.JTextField();
        tf_nombreempleadomodif = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        cb_modficarempleado = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_eliminarempleados = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        Panel_Producto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Panel_empleados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Panel_mterial = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Panel_lineaEnsablaje = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Ventana_Materiales.setTitle("Materiales");
        Ventana_Materiales.setBackground(new java.awt.Color(255, 255, 0));
        Ventana_Materiales.setResizable(false);

        PaneldePaneles.setBackground(new java.awt.Color(255, 204, 0));
        PaneldePaneles.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PaneldePanelesStateChanged(evt);
            }
        });
        PaneldePaneles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaneldePanelesMouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Inventario General");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 605, -1));

        tablamaterialver.setBackground(new java.awt.Color(204, 255, 102));
        tablamaterialver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero de Serie", "Material", "Descripcion", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablamaterialver);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 481, 150));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torretromp_p1/1.jpg"))); // NOI18N
        jLabel20.setText(" ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 380));

        PaneldePaneles.addTab("Ver Materiales", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        labelerroragregarmaterial.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        labelerroragregarmaterial.setForeground(new java.awt.Color(255, 0, 0));
        labelerroragregarmaterial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelerroragregarmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 163, 10));

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Agregar Material");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, 584, -1));
        jPanel2.add(Tf_Numseriematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 248, 163, -1));
        jPanel2.add(Tf_marcamaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 211, 163, -1));

        jLabel15.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Marca");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 211, 97, -1));

        jLabel16.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Numero de Serie");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 248, 97, -1));

        Ta_descripcionmaterial.setColumns(20);
        Ta_descripcionmaterial.setRows(5);
        jScrollPane3.setViewportView(Ta_descripcionmaterial);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 115, -1, -1));
        jPanel2.add(Tf_nombrematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 78, 163, -1));

        jLabel17.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Nombre");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 78, 97, -1));

        jLabel18.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Decripcion");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 115, 97, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torretromp_p1/1.jpg"))); // NOI18N
        jLabel23.setText(" ");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 380));

        PaneldePaneles.addTab("Agregar Nuevo Material", jPanel2);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_eliminarmateriales.setBackground(new java.awt.Color(204, 255, 102));
        tabla_eliminarmateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero de Serie", "Material", "Descripcion", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_eliminarmateriales);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 71, 481, 154));

        btn_eliminarmaterial.setText("Eliminar Material");
        btn_eliminarmaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarmaterialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarmaterialMouseEntered(evt);
            }
        });
        jPanel3.add(btn_eliminarmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 243, -1, -1));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Eliminar Materiales");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 605, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torretromp_p1/1.jpg"))); // NOI18N
        jLabel24.setText(" ");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 380));

        PaneldePaneles.addTab("Eliminar Material", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Reestablecer Valores");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 605, -1));

        Cb_materialamodificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cb_materialamodificarItemStateChanged(evt);
            }
        });
        jPanel4.add(Cb_materialamodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 68, 200, -1));

        jLabel14.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        jLabel14.setText("Material ");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 68, -1, 20));
        jPanel4.add(Tf_nombrematerialmodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 181, -1));

        Ta_descripcionmaterialmodif.setColumns(20);
        Ta_descripcionmaterialmodif.setRows(5);
        jScrollPane1.setViewportView(Ta_descripcionmaterialmodif);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 181, 60));
        jPanel4.add(Tf_marcamaterialmodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 181, -1));
        jPanel4.add(Tf_Numseriematerialmodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 181, -1));

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        jLabel9.setText("Numero de Serie");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        jLabel8.setText("Marca");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        jLabel7.setText("Decripcion");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        jLabel6.setText("Nombre");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jButton3.setText("Restablecer");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torretromp_p1/1.jpg"))); // NOI18N
        jLabel26.setText(" ");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 380));

        PaneldePaneles.addTab("Modificar Materiales", jPanel4);

        javax.swing.GroupLayout Ventana_MaterialesLayout = new javax.swing.GroupLayout(Ventana_Materiales.getContentPane());
        Ventana_Materiales.getContentPane().setLayout(Ventana_MaterialesLayout);
        Ventana_MaterialesLayout.setHorizontalGroup(
            Ventana_MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneldePaneles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Ventana_MaterialesLayout.setVerticalGroup(
            Ventana_MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneldePaneles)
        );

        Vnetana_Empleados.setBackground(new java.awt.Color(102, 102, 0));
        Vnetana_Empleados.setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 0));
        jTabbedPane1.setName("Empleados"); // NOI18N

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Ver Empleados");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 501, 42));

        Tabla_empleadosver.setBackground(new java.awt.Color(102, 255, 255));
        Tabla_empleadosver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Direccion", "Edad", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(Tabla_empleadosver);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 107, -1, 140));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torretromp_p1/1.jpg"))); // NOI18N
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 500, 370));

        jTabbedPane1.addTab("Ver Empleados", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Agregar Empleados");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 501, 42));

        jLabel21.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel21.setText("Nombre");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 81, -1, 19));

        jLabel22.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel22.setText("Direccion");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 119, -1, 19));

        jLabel25.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel25.setText("Identidad");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 157, -1, 19));

        jLabel27.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel27.setText("Edad");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 195, 29, 19));

        jLabel28.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel28.setText("Salario");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 232, -1, 19));

        tf_nombreempleados.setText("      ");
        jPanel6.add(tf_nombreempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 82, 226, -1));

        tf_identidadempleados.setText("      ");
        jPanel6.add(tf_identidadempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 158, 226, -1));

        tf_direccionempleados.setText("      ");
        jPanel6.add(tf_direccionempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 120, 226, -1));

        tf_salarioempleado.setText("      ");
        jPanel6.add(tf_salarioempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 233, 89, -1));

        tf_edadempleados.setText(" ");
        jPanel6.add(tf_edadempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 195, 43, -1));

        bt_agregarempleado.setText("Agregar");
        bt_agregarempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarempleadoMouseClicked(evt);
            }
        });
        jPanel6.add(bt_agregarempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 287, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torretromp_p1/1.jpg"))); // NOI18N
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 500, 370));

        jTabbedPane1.addTab("Agregar Empleados", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Modificar Datos");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 501, 42));

        tf_salarioempleadomodif.setText("      ");
        jPanel7.add(tf_salarioempleadomodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 259, 89, -1));

        tf_edadempleadomodif.setText(" ");
        jPanel7.add(tf_edadempleadomodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 222, 43, -1));

        jLabel30.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel30.setText("Salario");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 259, -1, -1));

        jLabel31.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel31.setText("Edad");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 222, 29, -1));

        tf_identidadempleadomodif.setText("      ");
        jPanel7.add(tf_identidadempleadomodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 185, 218, -1));

        jLabel32.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel32.setText("Identidad");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 185, 49, -1));

        jLabel33.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel33.setText("Direccion");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 148, -1, -1));

        tf_direccionempleadomodif.setText("      ");
        jPanel7.add(tf_direccionempleadomodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 148, 226, -1));

        tf_nombreempleadomodif.setText("      ");
        jPanel7.add(tf_nombreempleadomodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 111, 226, -1));

        jLabel34.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel34.setText("Nombre");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 111, -1, -1));

        jToggleButton2.setText("Aceptar");
        jPanel7.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 284, -1, -1));

        jPanel7.add(cb_modficarempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 75, 226, -1));

        jLabel36.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel36.setText("Empleado");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 78, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torretromp_p1/1.jpg"))); // NOI18N
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 500, 370));

        jTabbedPane1.addTab("Modificar Datos", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Eliminar Empleados");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 501, 42));

        ta_eliminarempleados.setBackground(new java.awt.Color(102, 204, 255));
        ta_eliminarempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Direccion", "Edad", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(ta_eliminarempleados);

        jPanel8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 102, -1, 133));

        jButton2.setText("Eliminar Empleado");
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 251, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torretromp_p1/1.jpg"))); // NOI18N
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 500, 370));

        jTabbedPane1.addTab("Eliminar Empleados", jPanel8);

        javax.swing.GroupLayout Vnetana_EmpleadosLayout = new javax.swing.GroupLayout(Vnetana_Empleados.getContentPane());
        Vnetana_Empleados.getContentPane().setLayout(Vnetana_EmpleadosLayout);
        Vnetana_EmpleadosLayout.setHorizontalGroup(
            Vnetana_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        Vnetana_EmpleadosLayout.setVerticalGroup(
            Vnetana_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Principal"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Productos");

        javax.swing.GroupLayout Panel_ProductoLayout = new javax.swing.GroupLayout(Panel_Producto);
        Panel_Producto.setLayout(Panel_ProductoLayout);
        Panel_ProductoLayout.setHorizontalGroup(
            Panel_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProductoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_ProductoLayout.setVerticalGroup(
            Panel_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 110, -1));

        Panel_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_empleadosMouseClicked(evt);
            }
        });

        jLabel3.setText("Empleados");

        javax.swing.GroupLayout Panel_empleadosLayout = new javax.swing.GroupLayout(Panel_empleados);
        Panel_empleados.setLayout(Panel_empleadosLayout);
        Panel_empleadosLayout.setHorizontalGroup(
            Panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_empleadosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        Panel_empleadosLayout.setVerticalGroup(
            Panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_empleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        Panel_mterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_mterialMouseClicked(evt);
            }
        });

        jLabel4.setText("Materiales");

        javax.swing.GroupLayout Panel_mterialLayout = new javax.swing.GroupLayout(Panel_mterial);
        Panel_mterial.setLayout(Panel_mterialLayout);
        Panel_mterialLayout.setHorizontalGroup(
            Panel_mterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_mterialLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_mterialLayout.setVerticalGroup(
            Panel_mterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_mterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_mterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 110, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Linea de Ensamblaje");

        javax.swing.GroupLayout Panel_lineaEnsablajeLayout = new javax.swing.GroupLayout(Panel_lineaEnsablaje);
        Panel_lineaEnsablaje.setLayout(Panel_lineaEnsablajeLayout);
        Panel_lineaEnsablajeLayout.setHorizontalGroup(
            Panel_lineaEnsablajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );
        Panel_lineaEnsablajeLayout.setVerticalGroup(
            Panel_lineaEnsablajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_lineaEnsablajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_lineaEnsablaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torretromp_p1/45.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_mterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_mterialMouseClicked
        this.Ventana_Materiales.pack();
        this.Ventana_Materiales.setLocationRelativeTo(this);
        //this.Ventana_Materiales.setModal();
        this.Ventana_Materiales.setVisible(true);


    }//GEN-LAST:event_Panel_mterialMouseClicked

    private void PaneldePanelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneldePanelesMouseClicked
        this.modelotablaaeliminar = new DefaultTableModel();
        /* this.tabla_eliminarmateriales.getModel();*/
        Object datos[] = new Object[4];
        modelotablaaeliminar.addColumn("Numero de Serie");
        modelotablaaeliminar.addColumn("Material");
        modelotablaaeliminar.addColumn("Descripcion");
        modelotablaaeliminar.addColumn("Marca");
        int contador = 0;
        if (listamateriales.head != null) {
            System.out.println("si hay algo");
            Nodo temporallista = listamateriales.head;
            System.out.println("tamano lista materiales" + listamateriales.size);
            while (temporallista.getNext() != null) {
                contador++;
                temporallista = temporallista.getNext();
            }
            System.out.println("tamano lista materiales" + contador);
            temporallista = listamateriales.head;
            for (int i = 0; i <= contador; i++) {
                datos[0] = ((Material) temporallista.getData()).getNumeroDeSerie();
                datos[1] = ((Material) temporallista.getData()).getNombre();
                datos[2] = ((Material) temporallista.getData()).getDescripcion();
                datos[3] = ((Material) temporallista.getData()).getMarca();
                this.modelotablaaeliminar.addRow(datos);
                temporallista = temporallista.getNext();
            }
            this.tabla_eliminarmateriales.setModel(modelotablaaeliminar);
        } else {
        }


    }//GEN-LAST:event_PaneldePanelesMouseClicked
    private void limpiaragregar() {
        this.Tf_nombrematerial.setText("");
        this.Ta_descripcionmaterial.setText("");
        this.Tf_marcamaterial.setText("");
        this.Tf_Numseriematerial.setText("");
    }
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre, descripcion, marca;
        int numeroDeSerie;

        if (!(this.Tf_nombrematerial.getText().equals("") || this.Ta_descripcionmaterial.getText().equals("")
                || this.Tf_Numseriematerial.getText().equals("") || this.Tf_marcamaterial.getText().equals(""))) {

            nombre = Tf_nombrematerial.getText();
            descripcion = Ta_descripcionmaterial.getText();
            marca = Tf_marcamaterial.getText();
            try {
                numeroDeSerie = Integer.parseInt(this.Tf_Numseriematerial.getText());

                Material materialnuevo = new Material(nombre, descripcion, marca, numeroDeSerie);
                Nodo materialconnodo = new Nodo(null, null, materialnuevo);
                Nodo temporallista = listamateriales.head;
                if (temporallista == null) {

                    System.out.println("null");
                    listamateriales.head = materialconnodo;
                    JOptionPane.showMessageDialog(null, "¡Nuevo material Agregado!");
                    limpiaragregar();
                } else {

                    while (temporallista != null) {

                        if (((Material) temporallista.getData()).getNombre().equals(((Material) materialconnodo.getData()).getNombre())) {

                            if (temporallista.getPila() != null) {
                                Nodo temporalpila = temporallista.getPila();
                                materialconnodo.setPila(temporalpila);
                                temporallista.setPila(materialconnodo);
                                JOptionPane.showMessageDialog(null, "¡Material Agregado a Su Categoria!");
                                System.out.println("agregado nueva head de cabeza ya habian elementos");
                                limpiaragregar();
                                break;
                            } else {
                                temporallista.setPila(materialconnodo);
                                JOptionPane.showMessageDialog(null, "¡Material Agregado a Su Categoria!");
                                System.out.println("agregado en cabeza principal de pilas no habian elementos pila");
                                limpiaragregar();
                                break;
                            }

                        }
                        temporallista = temporallista.getNext();

                        if (temporallista == null) {

                            Nodo temporal = listamateriales.head;
                            listamateriales.head = materialconnodo;
                            listamateriales.head.setNext(temporal);
                            JOptionPane.showMessageDialog(null, "¡Nuevo material Agregado!");
                            System.out.println("agregado como hermano de lista");
                            limpiaragregar();
                        }
                    }

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se admiten letras en la serie del material");
            }
        } else {
            labelerroragregarmaterial.setText("Hay campos vacios");
        }
    }//GEN-LAST:event_jButton1MouseClicked
    private void refrescartablamaterialeliminar() {
        this.modelotablaaeliminar = new DefaultTableModel();
        /* this.tabla_eliminarmateriales.getModel();*/
        Object datos[] = new Object[4];
        modelotablaaeliminar.addColumn("Numero de Serie");
        modelotablaaeliminar.addColumn("Material");
        modelotablaaeliminar.addColumn("Descripcion");
        modelotablaaeliminar.addColumn("Marca");
        int contador = 0;
        if (listamateriales.getHead() != null) {
            Nodo temporallista = listamateriales.getHead();
            while (temporallista.getNext() != null) {
                contador++;
                temporallista = temporallista.getNext();
            }
            temporallista = listamateriales.getHead();
            for (int i = 0; i <= contador; i++) {
                datos[0] = ((Material) temporallista.getData()).getNumeroDeSerie();
                datos[1] = ((Material) temporallista.getData()).getNombre();
                datos[2] = ((Material) temporallista.getData()).getDescripcion();
                datos[3] = ((Material) temporallista.getData()).getMarca();
                this.modelotablaaeliminar.addRow(datos);
                temporallista = temporallista.getNext();
            }
            this.tabla_eliminarmateriales.setModel(modelotablaaeliminar);
        } else {
            /* datos[0] = "";
            datos[1] = "";
            datos[2] = "";
            datos[3] = "";
            this.modelotablaaeliminar.addRow(datos);*/
            this.tabla_eliminarmateriales.setModel(modelotablaaeliminar);
        }

    }

    private void refrescartablamaverproducto() {
        this.modelotablaaeliminar = new DefaultTableModel();
        Object datos[] = new Object[4];
        modelotablaaeliminar.addColumn("Numero de Serie");
        modelotablaaeliminar.addColumn("Material");
        modelotablaaeliminar.addColumn("Descripcion");
        modelotablaaeliminar.addColumn("Marca");
        int contador = 0;
        if (listamateriales.getHead() != null) {
            Nodo temporallista = listamateriales.getHead();
            while (temporallista.getNext() != null) {
                contador++;
                temporallista = temporallista.getNext();
            }
            temporallista = listamateriales.getHead();
            for (int i = 0; i <= contador; i++) {
                datos[0] = ((Material) temporallista.getData()).getNumeroDeSerie();
                datos[1] = ((Material) temporallista.getData()).getNombre();
                datos[2] = ((Material) temporallista.getData()).getDescripcion();
                datos[3] = ((Material) temporallista.getData()).getMarca();
                this.modelotablaaeliminar.addRow(datos);
                temporallista = temporallista.getNext();
            }
            this.tablamaterialver.setModel(modelotablaaeliminar);
        } else {

            /*  datos[0] = "";
            datos[1] = "";
            datos[2] = "";
            datos[3] = "";
            this.modelotablaaeliminar.addRow(datos);*/
            this.tablamaterialver.setModel(modelotablaaeliminar);
        }

    }
    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked

    }//GEN-LAST:event_jPanel3MouseClicked

    private void btn_eliminarmaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarmaterialMouseClicked
        int indicematerialeliminar = this.tabla_eliminarmateriales.getSelectedRow();
        if (indicematerialeliminar != -1) {
            System.out.println("indice de la tabla " + indicematerialeliminar);
            listamateriales.delete(indicematerialeliminar);
            refrescartablamaterialeliminar();
            refrescartablamaverproducto();
        }


    }//GEN-LAST:event_btn_eliminarmaterialMouseClicked

    private void btn_eliminarmaterialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarmaterialMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarmaterialMouseEntered
    private void Cb_actualizar() {
        this.Cb_materialamodificar.setModel(new DefaultComboBoxModel());
        Nodo temporallista = listamateriales.getHead();
        if (temporallista == null) {
            this.Cb_materialamodificar.setModel(new DefaultComboBoxModel());
        } else {
            int contador = 0;

            while (temporallista != null) {
                contador++;
                temporallista = temporallista.getNext();
            }
            temporallista = listamateriales.getHead();
            for (int i = 0; i <= contador; i++) {
                if (temporallista != null) {
                    this.Cb_materialamodificar.addItem(((Material) temporallista.getData()).getNombre());
                    temporallista = temporallista.getNext();
                }
            }
            this.tablamaterialver.setModel(modelotablaaeliminar);
        }
    }
    private void PaneldePanelesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PaneldePanelesStateChanged
        if (this.PaneldePaneles.getSelectedIndex() == 2) {
            Cb_actualizar();
        } else if (this.PaneldePaneles.getSelectedIndex() == 0) {
            refrescartablamaverproducto();
        }

    }//GEN-LAST:event_PaneldePanelesStateChanged

    private void Cb_materialamodificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cb_materialamodificarItemStateChanged
        int contador = 0, indice = this.Cb_materialamodificar.getSelectedIndex();
        Nodo tempolista = listamateriales.getHead();

        while (tempolista != null) {
            if (contador == indice) {
                this.Tf_nombrematerialmodif.setText(((Material) tempolista.getData()).getNombre());
                this.Ta_descripcionmaterialmodif.setText(((Material) tempolista.getData()).getDescripcion());
                this.Tf_marcamaterialmodif.setText(((Material) tempolista.getData()).getMarca());
                this.Tf_Numseriematerialmodif.setText(Integer.toString(((Material) tempolista.getData()).getNumeroDeSerie()));
                break;
            }
            contador++;
            tempolista = tempolista.getNext();
        }

    }//GEN-LAST:event_Cb_materialamodificarItemStateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int indice = this.Cb_materialamodificar.getSelectedIndex();
        Nodo tempolista = listamateriales.getHead();
        int contador = 0;
        while (tempolista != null) {
            if (contador == indice) {
                if (!(this.Tf_nombrematerialmodif.getText().equals(" ") || this.Tf_nombrematerialmodif.getText().equals(" ") || this.Tf_marcamaterialmodif.getText().equals(" ")
                        || this.Tf_Numseriematerialmodif.getText().equals(" "))) {
                    ((Material) tempolista.getData()).setNombre(this.Tf_nombrematerialmodif.getText());
                    ((Material) tempolista.getData()).setDescripcion(this.Ta_descripcionmaterialmodif.getText());
                    ((Material) tempolista.getData()).setMarca(this.Tf_marcamaterialmodif.getText());
                    try {
                        ((Material) tempolista.getData()).setNumeroDeSerie(Integer.parseInt(this.Tf_Numseriematerialmodif.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "¡No se admiten letras en la serie del Material!");
                        contador--;
                    }
                    JOptionPane.showMessageDialog(null, "¡Modificado!");
                    this.Tf_nombrematerialmodif.setText("");
                    this.Ta_descripcionmaterialmodif.setText("");
                    this.Tf_marcamaterialmodif.setText("");
                    this.Tf_Numseriematerialmodif.setText("");

                } else {
                    JOptionPane.showMessageDialog(null, "¡Error!, hay campos vacios");
                }

            }
            contador++;
            tempolista = tempolista.getNext();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void Panel_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_empleadosMouseClicked
        this.Vnetana_Empleados.pack();
        this.Vnetana_Empleados.setLocationRelativeTo(this);
        this.Vnetana_Empleados.setVisible(true);
    }//GEN-LAST:event_Panel_empleadosMouseClicked

    private void bt_agregarempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarempleadoMouseClicked
        String nombre, direccion;
        int id, edad;
        double salario;

        nombre = this.tf_nombreempleados.getText();
        direccion = this.tf_direccionempleados.getText();

        id = Integer.parseInt(this.tf_identidadempleados.getText());
        edad = Integer.parseInt(this.tf_edadempleados.getText());
        salario = Double.parseDouble(this.tf_salarioempleado.getText());
        Empleado nuevoempleado = new Empleado(nombre, direccion, id, edad, salario);
        Nodo nodonuevoempleado = new Nodo(null, null, nuevoempleado);
        colaempleados.Queue(nodonuevoempleado);

        //agrega a l lista
        if (listaempleados.getHead() != null) {
            listaempleados.setHead(nodonuevoempleado);
            System.out.println("agegado a la cabeza de lista empleado");
        } else {
            Nodo tempolistaemplea = listaempleados.getHead();
            int contador = -1;
            while (tempolistaemplea != null) {
                contador++;
                tempolistaemplea = tempolistaemplea.getNext();
            }
            System.out.println("agegado hermano empleado");
            listaempleados.insert(contador, nodonuevoempleado);
        }
        //


    }//GEN-LAST:event_bt_agregarempleadoMouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_materialamodificar;
    private javax.swing.JPanel Panel_Producto;
    private javax.swing.JPanel Panel_empleados;
    private javax.swing.JPanel Panel_lineaEnsablaje;
    private javax.swing.JPanel Panel_mterial;
    private javax.swing.JTabbedPane PaneldePaneles;
    private javax.swing.JTextArea Ta_descripcionmaterial;
    private javax.swing.JTextArea Ta_descripcionmaterialmodif;
    private javax.swing.JTable Tabla_empleadosver;
    private javax.swing.JTextField Tf_Numseriematerial;
    private javax.swing.JTextField Tf_Numseriematerialmodif;
    private javax.swing.JTextField Tf_marcamaterial;
    private javax.swing.JTextField Tf_marcamaterialmodif;
    private javax.swing.JTextField Tf_nombrematerial;
    private javax.swing.JTextField Tf_nombrematerialmodif;
    private javax.swing.JDialog Ventana_Materiales;
    private javax.swing.JDialog Vnetana_Empleados;
    private javax.swing.JToggleButton bt_agregarempleado;
    private javax.swing.JButton btn_eliminarmaterial;
    private javax.swing.JComboBox<String> cb_modficarempleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel labelerroragregarmaterial;
    private javax.swing.JTable ta_eliminarempleados;
    private javax.swing.JTable tabla_eliminarmateriales;
    private javax.swing.JTable tablamaterialver;
    private javax.swing.JTextField tf_direccionempleadomodif;
    private javax.swing.JTextField tf_direccionempleados;
    private javax.swing.JTextField tf_edadempleadomodif;
    private javax.swing.JTextField tf_edadempleados;
    private javax.swing.JTextField tf_identidadempleadomodif;
    private javax.swing.JTextField tf_identidadempleados;
    private javax.swing.JTextField tf_nombreempleadomodif;
    private javax.swing.JTextField tf_nombreempleados;
    private javax.swing.JTextField tf_salarioempleado;
    private javax.swing.JTextField tf_salarioempleadomodif;
    // End of variables declaration//GEN-END:variables
    MaterialesListaPilas listamateriales = new MaterialesListaPilas();
    ColaEmpleados colaempleados = new ColaEmpleados();
    Lista listaempleados = new Lista();
    CatalogodeProductosTDALinkList catalogo = new CatalogodeProductosTDALinkList();
    DefaultTableModel modelotablaaeliminar;
}
